apiVersion: apps/v1
kind: Deployment
metadata:
  name: exhibitor
  namespace: s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exhibitor
  template:
    metadata:
      labels:
        app: exhibitor
    spec:
      containers:
      - name: exhibitor
        image: netflixoss/exhibitor:1.5.2
        args:
        - "--port=8080"
        - "--defaultconfig=/exhibitor/defaults.conf"
        - "--configtype=file"
        - "--configfile=/exhibitor/exhibitor.conf"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: exhibitor
  namespace: s
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: exhibitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoonavigator
  namespace: s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoonavigator
  template:
    metadata:
      labels:
        app: zoonavigator
    spec:
      containers:
      - name: zoonavigator
        image: obsidiandynamics/zoonavigator:latest
        env:
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper:2181"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: zoonavigator
  namespace: s
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: zoonavigator