// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/21/2025, 10:06:17 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/plugins/**/*.{js,ts,mjs}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/composables/**/*.{js,ts,mjs}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/utils/**/*.{js,ts,mjs}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/fengwei.lee_simpletr/Desktop/REPO/p/SampleProject/news-hub/project/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;